/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        /** Create Application */
        post: operations["create_application_api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Application */
        patch: operations["patch_application_api_v1_applications__application_id__patch"];
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke this session's tokens.
         *
         *     Both tokens are revoked: dropping only the access token would leave the
         *     refresh token able to mint a fresh one, which is not a logout.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Permanently delete the account and everything owned by it.
         *
         *     Hard delete, by design (see docs/adr/0016-deletion-policy.md): this is the
         *     user's own data-erasure path, so leaving soft-deleted rows behind would
         *     defeat the point. Every owned table cascades from `users`, including the
         *     encrypted GitHub token.
         */
        delete: operations["delete_account_api_v1_auth_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Claims
         * @description Backs the resume workspace's provenance rail (PRD §11.4): click a
         *     bullet, see exactly which repository/file it traces back to.
         */
        get: operations["get_document_claims_api_v1_documents__document_id__claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Document Endpoint
         * @description Synchronous (not queued): one bounded Playwright render + parse-back
         *     validation cycle, same rationale as resume upload and positioning.
         */
        post: operations["export_document_endpoint_api_v1_documents__document_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Document Pdf */
        get: operations["download_document_pdf_api_v1_documents__document_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Document Html
         * @description Live preview for the resume workspace (checklist §10.7).
         *
         *     Runs the *same* template renderer the PDF export uses, minus the Chromium
         *     step, so what the user sees while switching templates is what the export
         *     will contain — not a separate React approximation that can drift from the
         *     real output. Nothing is persisted; this is read-only.
         */
        get: operations["preview_document_html_api_v1_documents__document_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run Events */
        get: operations["stream_run_events_api_v1_events_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence */
        get: operations["list_evidence_api_v1_evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence Graph */
        get: operations["get_evidence_graph_api_v1_evidence_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Evidence */
        post: operations["search_evidence_api_v1_evidence_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_v1_evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Evidence
         * @description Approve/reject/mark-private (PRD §9.1 Evidence Review). Only status is
         *     user-editable in V1 — editing claim text is deferred; a user who disagrees
         *     with a claim rejects it rather than rewriting AI-generated text, which would
         *     reintroduce the provenance problem ProofHire exists to solve.
         */
        patch: operations["patch_evidence_api_v1_evidence__evidence_id__patch"];
        trace?: never;
    };
    "/api/v1/generation-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Generation Run */
        get: operations["get_generation_run_api_v1_generation_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_v1_github_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/github/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect */
        post: operations["connect_api_v1_github_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/github/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Disconnect
         * @description Disconnect GitHub: drop the stored OAuth token and the repositories it
         *     gave access to.
         *
         *     Evidence already extracted is deliberately kept — it belongs to the user's
         *     profile, not to the connection, and silently destroying a reviewed evidence
         *     graph because a token was disconnected would be a nasty surprise. Use
         *     account deletion to erase everything.
         */
        delete: operations["disconnect_api_v1_github_connection_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/github/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Repositories
         * @description Lists repositories already known to ProofHire. Call POST /github/repositories/refresh
         *     first (or after connecting) to pull the latest list from GitHub.
         */
        get: operations["list_repositories_api_v1_github_repositories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/github/repositories/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Repositories
         * @description Pulls the user's repository list from GitHub and upserts local rows.
         *     Does not fetch file content — that happens in POST /github/sync.
         */
        post: operations["refresh_repositories_api_v1_github_repositories_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/github/repositories/{repository_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Repository */
        patch: operations["patch_repository_api_v1_github_repositories__repository_id__patch"];
        trace?: never;
    };
    "/api/v1/github/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Sync */
        post: operations["trigger_sync_api_v1_github_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/github/sync/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sync Status */
        get: operations["get_sync_status_api_v1_github_sync__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture Job */
        post: operations["capture_job_api_v1_jobs_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Job Endpoint */
        post: operations["analyze_job_endpoint_api_v1_jobs__job_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job Endpoint
         * @description Request cancellation of the job's running pipeline (checklist §12.7).
         *
         *     Cooperative: sets a flag the worker checks between LLM calls, so it takes
         *     effect within one call rather than instantly. 202 because the cancel is
         *     requested, not yet observed; the job's status becomes `cancelled` when
         *     the worker sees the flag, and a job that isn't running just clears it.
         */
        post: operations["cancel_job_endpoint_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Coverage
         * @description Evidence Coverage Matrix (PRD §18). A requirement with no EvidenceMatch
         *     row is an implicit Gap — the coverage engine never even retrieved a
         *     plausible candidate for it (PRD §17).
         */
        get: operations["get_coverage_api_v1_jobs__job_id__coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Generate */
        post: operations["trigger_generate_api_v1_jobs__job_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/positioning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Positioning
         * @description Synchronous (not queued): one bounded LLM call, same rationale as resume
         *     upload. Not persisted — this is an ephemeral preview the user reviews
         *     before generating; POST /jobs/{id}/generate recomputes it internally as
         *     part of the same pipeline run, so nothing is lost by not storing it here.
         */
        post: operations["get_positioning_api_v1_jobs__job_id__positioning_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Requirements */
        get: operations["get_requirements_api_v1_jobs__job_id__requirements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profile Facts */
        get: operations["list_profile_facts_api_v1_profile_facts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/facts/{fact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Profile Fact
         * @description A user can correct a misextracted value before confirming it — the fact
         *     guard only ever checks against *confirmed* data going forward (Phase 5
         *     generation reads confirmed=True facts), so an unconfirmed fact with a typo
         *     is safe to fix here rather than re-uploading the whole resume.
         */
        patch: operations["patch_profile_fact_api_v1_profile_facts__fact_id__patch"];
        trace?: never;
    };
    "/api/v1/profile/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Resume
         * @description Synchronous (not queued): a single resume is one bounded LLM call, unlike
         *     repository ingestion or JD analysis which can involve many files/requirements.
         *     Immediate feedback is worth more here than the async/SSE pattern used
         *     elsewhere in the pipeline.
         */
        post: operations["upload_resume_api_v1_profile_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness gates traffic, so it must reflect every dependency a request
         *     can fail on. Redis is included because token revocation fails closed
         *     (security/token_revocation.py): with Redis down, every authenticated
         *     request returns 503, which is not a state to route traffic into.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
        };
        /** ApplicationCreateRequest */
        ApplicationCreateRequest: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /** ApplicationPatch */
        ApplicationPatch: {
            stage: components["schemas"]["ApplicationStage"];
        };
        /** ApplicationPublic */
        ApplicationPublic: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            stage: components["schemas"]["ApplicationStage"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ApplicationStage
         * @enum {string}
         */
        ApplicationStage: "saved" | "analyzing" | "ready" | "applied" | "screen" | "interview" | "offer" | "rejected" | "archived";
        /** Body_upload_resume_api_v1_profile_resume_post */
        Body_upload_resume_api_v1_profile_resume_post: {
            /** File */
            file: string;
        };
        /**
         * ClaimVerificationStatus
         * @enum {string}
         */
        ClaimVerificationStatus: "supported" | "partially_supported" | "unsupported" | "contradictory";
        /** ConnectResponse */
        ConnectResponse: {
            /** Authorize Url */
            authorize_url: string;
        };
        /** CoverageRow */
        CoverageRow: {
            /** Action */
            action: string;
            category: components["schemas"]["RequirementCategory"];
            /** Confidence */
            confidence: number | null;
            /** Evidence Id */
            evidence_id: string | null;
            /** Evidence Repository */
            evidence_repository: string | null;
            /** Evidence Title */
            evidence_title: string | null;
            /** Explanation */
            explanation: string;
            /** Importance */
            importance: number;
            match_label: components["schemas"]["MatchLabel"];
            /** Required */
            required: boolean;
            /**
             * Requirement Id
             * Format: uuid
             */
            requirement_id: string;
            /** Requirement Text */
            requirement_text: string;
        };
        /**
         * DocumentType
         * @enum {string}
         */
        DocumentType: "resume" | "cover_letter";
        /** EvidenceDetail */
        EvidenceDetail: {
            /** Confidence */
            confidence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            evidence_type: components["schemas"]["EvidenceType"];
            /** Extraction Method */
            extraction_method: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Normalized Claim */
            normalized_claim: string;
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Skills */
            skills: string[];
            /** Sources */
            sources: components["schemas"]["EvidenceSourcePublic"][];
            status: components["schemas"]["EvidenceStatus"];
            /** Title */
            title: string;
        };
        /** EvidenceGraph */
        EvidenceGraph: {
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Evidence Limit */
            evidence_limit: number;
            /** Job Id */
            job_id?: string | null;
            /** Job Status */
            job_status?: string | null;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** EvidencePatch */
        EvidencePatch: {
            status: components["schemas"]["EvidenceStatus"];
        };
        /** EvidencePublic */
        EvidencePublic: {
            /** Confidence */
            confidence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            evidence_type: components["schemas"]["EvidenceType"];
            /** Extraction Method */
            extraction_method: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Normalized Claim */
            normalized_claim: string;
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            status: components["schemas"]["EvidenceStatus"];
            /** Title */
            title: string;
        };
        /** EvidenceSearchHit */
        EvidenceSearchHit: {
            /** Confidence */
            confidence: number;
            evidence_type: components["schemas"]["EvidenceType"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Normalized Claim */
            normalized_claim: string;
            /** Score */
            score: number;
            /** Title */
            title: string;
        };
        /** EvidenceSearchRequest */
        EvidenceSearchRequest: {
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /** Text */
            text: string;
        };
        /** EvidenceSourcePublic */
        EvidenceSourcePublic: {
            /** Commit Sha */
            commit_sha: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Line End */
            line_end: number | null;
            /** Line Start */
            line_start: number | null;
            /** Locator */
            locator: string;
            /** Relevance */
            relevance: number;
            /**
             * Source Artifact Id
             * Format: uuid
             */
            source_artifact_id: string;
        };
        /**
         * EvidenceStatus
         * @enum {string}
         */
        EvidenceStatus: "candidate" | "confirmed" | "rejected" | "private" | "stale";
        /**
         * EvidenceType
         * @enum {string}
         */
        EvidenceType: "skill_usage" | "architecture" | "implementation" | "integration" | "deployment" | "testing" | "ml_model" | "data_pipeline" | "performance_metric" | "ownership" | "contribution" | "feature";
        /** ExportResponse */
        ExportResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Overflowed
             * @default false
             */
            overflowed: boolean;
            /** Page Count */
            page_count?: number | null;
            /** Pdf Available */
            pdf_available: boolean;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /** @default resume */
            document_type: components["schemas"]["DocumentType"];
            /** @default conservative */
            mode: components["schemas"]["TailoringMode"];
        };
        /** GenerateResponse */
        GenerateResponse: {
            /** Generation Run Id */
            generation_run_id?: string | null;
            /**
             * Status
             * @default queued
             */
            status: string;
        };
        /** GeneratedClaimPublic */
        GeneratedClaimPublic: {
            /** Claim Text */
            claim_text: string;
            /** Claim Type */
            claim_type: string;
            /** Confidence */
            confidence: number;
            /** Evidence Id */
            evidence_id?: string | null;
            /** Evidence Repository */
            evidence_repository?: string | null;
            /** Evidence Title */
            evidence_title?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Locator */
            source_locator?: string | null;
            verification_status: components["schemas"]["ClaimVerificationStatus"];
        };
        /** GeneratedDocumentPublic */
        GeneratedDocumentPublic: {
            /** Content Json */
            content_json: {
                [key: string]: unknown;
            };
            /**
             * Generation Run Id
             * Format: uuid
             */
            generation_run_id: string;
            /** Html Ref */
            html_ref?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Page Count */
            page_count?: number | null;
            /** Pdf Ref */
            pdf_ref?: string | null;
            /** Plaintext Ref */
            plaintext_ref?: string | null;
            /** Template Id */
            template_id: string;
            type: components["schemas"]["DocumentType"];
            /** Version */
            version: number;
        };
        /** GenerationRunPublic */
        GenerationRunPublic: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Estimated Cost */
            estimated_cost: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Latency Ms */
            latency_ms: number;
            /** Pipeline Version */
            pipeline_version: string;
            /** Prompt Versions */
            prompt_versions: string[];
            status: components["schemas"]["GenerationRunStatus"];
            /** Token Usage */
            token_usage: {
                [key: string]: unknown;
            };
        };
        /**
         * GenerationRunStatus
         * @enum {string}
         */
        GenerationRunStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** GraphEdge */
        GraphEdge: {
            /**
             * Explanation
             * @default
             */
            explanation: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "contains" | "demonstrates" | "matches";
            /** Source */
            source: string;
            status?: components["schemas"]["MatchLabel"] | null;
            /** Target */
            target: string;
            /** Weight */
            weight: number;
        };
        /** GraphNode */
        GraphNode: {
            /** Confidence */
            confidence?: number | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Evidence Id */
            evidence_id?: string | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "project" | "skill" | "architecture" | "evidence" | "requirement";
            /** Label */
            label: string;
            /** Repository Id */
            repository_id?: string | null;
            /** Required */
            required?: boolean | null;
            /** Sources */
            sources?: components["schemas"]["GraphSource"][];
            /** Status */
            status?: string | null;
        };
        /** GraphSource */
        GraphSource: {
            /** Commit Sha */
            commit_sha: string;
            /** Line End */
            line_end?: number | null;
            /** Line Start */
            line_start?: number | null;
            /** Locator */
            locator: string;
            /** Url */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobCaptureRequest */
        JobCaptureRequest: {
            /**
             * Capture Id
             * Format: uuid
             */
            capture_id?: string;
            /** Captured At */
            captured_at?: string | null;
            /** Page Url */
            page_url?: string | null;
            /** Selected Text */
            selected_text: string;
            /** Title */
            title?: string | null;
        };
        /** JobCreateRequest */
        JobCreateRequest: {
            /** Source Text */
            source_text?: string | null;
            /** Source Url */
            source_url?: string | null;
        };
        /** JobPublic */
        JobPublic: {
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Company */
            company: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Location */
            location: string | null;
            /** Role */
            role: string | null;
            /** Seniority */
            seniority: string | null;
            /** Source Url */
            source_url: string | null;
            /** Status */
            status: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /**
         * MatchLabel
         * @enum {string}
         */
        MatchLabel: "strong" | "partial" | "gap" | "unknown";
        /** PositioningResponse */
        PositioningResponse: {
            /** Gaps To Avoid */
            gaps_to_avoid: string[];
            /** Project Priority */
            project_priority: string[];
            /** Skills Priority */
            skills_priority: string[];
            /** Target Identity */
            target_identity: string;
            /** Themes */
            themes: string[];
        };
        /** ProfileFactPatch */
        ProfileFactPatch: {
            /** Confirmed */
            confirmed?: boolean | null;
            /** Value Json */
            value_json?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProfileFactPublic */
        ProfileFactPublic: {
            /** Confirmed */
            confirmed: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Immutable */
            immutable: boolean;
            /** Source */
            source: string;
            type: components["schemas"]["ProfileFactType"];
            /** Value Json */
            value_json: {
                [key: string]: unknown;
            };
        };
        /**
         * ProfileFactType
         * @enum {string}
         */
        ProfileFactType: "employment" | "education" | "award" | "certification" | "contact" | "summary_fact";
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RepositoryPatch */
        RepositoryPatch: {
            /** Selected */
            selected: boolean;
        };
        /** RepositoryPublic */
        RepositoryPublic: {
            /** Default Branch */
            default_branch: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Language Summary */
            language_summary: {
                [key: string]: unknown;
            };
            /** Last Analyzed Sha */
            last_analyzed_sha: string | null;
            /** Last Commit Sha */
            last_commit_sha: string | null;
            /** Name */
            name: string;
            /** Owner */
            owner: string;
            /** Selected */
            selected: boolean;
            /** Stars */
            stars: number;
            sync_status: components["schemas"]["SyncStatus"];
            /** Url */
            url: string;
            /** Visibility */
            visibility: string;
        };
        /**
         * RequirementCategory
         * @enum {string}
         */
        RequirementCategory: "skill" | "experience" | "responsibility" | "domain" | "education" | "tooling" | "soft_skill" | "seniority";
        /** RequirementPublic */
        RequirementPublic: {
            category: components["schemas"]["RequirementCategory"];
            /** Confidence */
            confidence: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Importance */
            importance: number;
            /** Normalized */
            normalized: string[];
            /** Required */
            required: boolean;
            /** Text */
            text: string;
        };
        /** SignupRequest */
        SignupRequest: {
            /** Display Name */
            display_name?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * SyncStatus
         * @enum {string}
         */
        SyncStatus: "idle" | "queued" | "syncing" | "completed" | "failed";
        /** SyncStatusResponse */
        SyncStatusResponse: {
            /** Error */
            error: string | null;
            /** Repository Ids */
            repository_ids: string[];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            status: components["schemas"]["SyncStatus"];
        };
        /** SyncTriggerRequest */
        SyncTriggerRequest: {
            /** Repository Ids */
            repository_ids: string[];
        };
        /** SyncTriggerResponse */
        SyncTriggerResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            status: components["schemas"]["SyncStatus"];
        };
        /**
         * TailoringMode
         * @enum {string}
         */
        TailoringMode: "conservative" | "full";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_api_v1_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_application_api_v1_applications__application_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    delete_account_api_v1_auth_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedDocumentPublic"][];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedDocumentPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_claims_api_v1_documents__document_id__claims_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedClaimPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_document_endpoint_api_v1_documents__document_id__export_post: {
        parameters: {
            query?: {
                template?: ("ats_minimal" | "technical_dense" | "modern_editorial") | null;
                page_size?: "Letter" | "A4";
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_document_pdf_api_v1_documents__document_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_document_html_api_v1_documents__document_id__preview_get: {
        parameters: {
            query?: {
                template?: ("ats_minimal" | "technical_dense" | "modern_editorial") | null;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_v1_events_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_api_v1_evidence_get: {
        parameters: {
            query?: {
                repository_id?: string | null;
                evidence_type?: components["schemas"]["EvidenceType"] | null;
                status?: components["schemas"]["EvidenceStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_graph_api_v1_evidence_graph_get: {
        parameters: {
            query?: {
                job_id?: string | null;
                repository_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_evidence_api_v1_evidence_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceSearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_v1_evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_evidence_api_v1_evidence__evidence_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidencePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_run_api_v1_generation_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationRunPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_api_v1_github_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_api_v1_github_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectResponse"];
                };
            };
        };
    };
    disconnect_api_v1_github_connection_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_repositories_api_v1_github_repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryPublic"][];
                };
            };
        };
    };
    refresh_repositories_api_v1_github_repositories_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryPublic"][];
                };
            };
        };
    };
    patch_repository_api_v1_github_repositories__repository_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_sync_api_v1_github_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncTriggerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncTriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sync_status_api_v1_github_sync__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_job_api_v1_jobs_capture_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_job_endpoint_api_v1_jobs__job_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_endpoint_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coverage_api_v1_jobs__job_id__coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_generate_api_v1_jobs__job_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_positioning_api_v1_jobs__job_id__positioning_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositioningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_requirements_api_v1_jobs__job_id__requirements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profile_facts_api_v1_profile_facts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileFactPublic"][];
                };
            };
        };
    };
    patch_profile_fact_api_v1_profile_facts__fact_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileFactPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileFactPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_resume_api_v1_profile_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_v1_profile_resume_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileFactPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
